[versions]
micronaut-plugin = "4.6.2"
graalvm-native-plugin = "0.11.4"
micronaut-platform = "4.10.7"
test-logger-plugin = "4.0.0"
testcontainers = "2.0.3"
testcontainers-gitserver = "0.12.0"
commons-codec = "1.21.0"
clique = "v2.0.0"
clique-themes = "v0.0.1"

[libraries]
micronaut-inject-java = { module = "io.micronaut:micronaut-inject-java" }
picocli-codegen = { module = "info.picocli:picocli-codegen" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor" }
micronaut-picocli = { module = "io.micronaut.picocli:micronaut-picocli" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson" }
logback-classic = { module = "ch.qos.logback:logback-classic" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
micronaut-test-junit5 = { module = "io.micronaut.test:micronaut-test-junit5" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-gitserver = { module = "io.github.sparsick.testcontainers.gitserver:testcontainers-gitserver", version.ref = "testcontainers-gitserver" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
clique = { module = "com.github.kusoroadeolu:Clique", version.ref = "clique" }
clique-themes = { module = "com.github.kusoroadeolu:clique-themes", version.ref = "clique-themes" }

[plugins]
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-plugin" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native-plugin" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger-plugin" }
